version: '3'
services:
  test:
    image: maven:3-jdk-11
    command: bash -c "cd /app && cp sources.list /etc/apt/ && cp settings.xml /root/.m2/ && mvn -Dtest.usecase.enabled=true test"
    environment:
      TZ: Asia/Shanghai
      SBIP_DEBUG: 'false'
      SBIP_LOGGING_LEVEL_REQUEST: INFO
    volumes:
      - ~/.m2:/root/.m2
      - ./:/app
    